development:
  adapter: postgresql
  encoding: utf8
  database: task-manager
  pool: 5
  host: localhost
  username: oce
  password: pwd
  port: 15432

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>